-- STORED PROCEDURE
-- Compute the average amount of product of a brand and then use it to modify the quantity of product specified by user in the save_to_shopping_cart relation

CREATE OR REPLACE PROCEDURE func1(vpid IN NUMBER, vbrand IN VARCHAR2) 
IS
    v_amount NUMBER;
BEGIN
    -- Compute the average amount of the specified brand
    SELECT AVG(amount) INTO v_amount
    FROM product
    WHERE brand = vbrand;
    
    -- Update the quantity of the specified product in the save_to_shopping_carts table
    UPDATE save_to_shopping_cart 
    SET quantity = v_amount 
    WHERE pid = vpid;
    
    -- Output the computed average amount
    DBMS_OUTPUT.PUT_LINE('Average amount: ' || v_amount);
END;
/

-- EXECUTE PROCEDURE
BEGIN
    func1(8, 'Microsoft');
END;
/

-- RECOVER QUANTITY
UPDATE save_to_shopping_cart 
SET quantity = 1 
WHERE pid = 8;

-- TRIGGER PROCEDURE
-- Create a table to audit changes in the shopping cart
CREATE TABLE shoppingcart_audits (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid INT NOT NULL,
    pid INT NOT NULL,
    quantity INT NOT NULL,
    changed_on TIMESTAMP NOT NULL
);

-- Create or replace the function to log changes in shopping cart quantity
CREATE OR REPLACE TRIGGER shoppingcart_quantity_changes
BEFORE UPDATE
ON save_to_shopping_cart
FOR EACH ROW
BEGIN
    -- Insert a record into the audit table if the quantity changes
    IF :NEW.quantity <> :OLD.quantity THEN
        INSERT INTO shoppingcart_audits (userid, pid, quantity, changed_on)
        VALUES (:OLD.userid, :OLD.pid, :OLD.quantity, SYSTIMESTAMP);
    END IF;
END;
/
